In [1]:
import numpy as np

#making an array

In [5]:
%time
data = np.random.randn(2, 3)
data

Wall time: 0 ns


array([[-1.77963459,  0.64787472,  1.53065569],
       [ 0.35456845,  0.06797769,  0.28977593]])

In [4]:
%time
data1 = np.random.rand(5,4)
data1

Wall time: 0 ns


array([[0.36671634, 0.01166798, 0.23830657, 0.44330598],
       [0.55350932, 0.08471162, 0.61872623, 0.87027483],
       [0.37647238, 0.93435407, 0.17268772, 0.47941477],
       [0.59710585, 0.66932906, 0.81974582, 0.20347861],
       [0.22020512, 0.73150399, 0.69307045, 0.51998625]])

#mathematical operations on array

In [6]:
data * 2

array([[-3.55926919,  1.29574945,  3.06131138],
       [ 0.70913689,  0.13595538,  0.57955186]])

In [8]:
data + data

array([[-3.55926919,  1.29574945,  3.06131138],
       [ 0.70913689,  0.13595538,  0.57955186]])

#self defined array

In [21]:
arr = np.array([2,4,6,8,10,12,14])

In [22]:
arr * 3

array([ 6, 12, 18, 24, 30, 36, 42])

In [23]:
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[ 2  4  6  8 10 12 14]


In [26]:
arr1 = np.array([1,2,3,4,5,6,7]) * 2
arr

array([ 2,  4,  6,  8, 10, 12, 14])

In [28]:
arr1 = np.random.rand(4) * 200
arr1

array([142.37798044,   5.0971944 ,  41.47890859, 185.26033244])

Dimension of an array ndim

In [29]:
arr1.ndim

1

In [30]:
data.ndim

2

Shape of an array

In [31]:
arr1.shape

(4,)

In [32]:
data.shape

(2, 3)

Two dimensional arrays

In [34]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


Zeros Onces and Empty arrays

In [38]:
zeroArr = np.zeros(10)
print(zeroArr)
print(zeroArr.ndim)
print(zeroArr.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1
(10,)


In [40]:
zeroArr1 = np.zeros((4,5))
print(zeroArr1)
print(zeroArr1.ndim)
print(zeroArr1.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2
(4, 5)


In [42]:
emp = np.empty((2, 3, 2))
print(emp)
print(emp.ndim)
print(emp.shape)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
3
(2, 3, 2)


In [43]:
onesArr = np.ones(10)
print(onesArr)
print(onesArr.ndim)
print(onesArr.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
1
(10,)


Arange function

In [44]:
np.arange(8)


array([0, 1, 2, 3, 4, 5, 6, 7])

In [48]:
a = np.array([2.2, 3.3, 4.4, 5.5, 6.6], dtype=np.float)
a.dtype

dtype('float64')

In [49]:
a.astype(int)


array([2, 3, 4, 5, 6])

Boolean Dtypes

In [51]:
rabiya = np.array([[1,2,3,4,5],[5,4,3,2,1]])
sara = np.array([[5,4,3,2,1],[1,2,3,4,5]])
print(rabiya)
print(sara)
rabiya > sara

[[1 2 3 4 5]
 [5 4 3 2 1]]
[[5 4 3 2 1]
 [1 2 3 4 5]]


array([[False, False, False,  True,  True],
       [ True,  True, False, False, False]])

Ravel //// Reshape

In [53]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b = np.ravel(b)
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
b = np.arange(1,9).reshape(2,4)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
twoD = np.arange(12).reshape(4,3)
twoD

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
threeD = twoD.reshape(2,2,3)
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [62]:
threeD = np.array([[[1,2,3],[4,5,6]] ,[[100,200,300],[400,500,600]]])
threeD

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[100, 200, 300],
        [400, 500, 600]]])

multiplication: rows of 1st matrix = cols of 2nd matrix

In [63]:
twoD2 = np.arange(8).reshape(2,4)

In [65]:
twoD2@twoD

array([[ 42,  48,  54],
       [114, 136, 158]])

In [66]:
np.dot(twoD2,twoD)

array([[ 42,  48,  54],
       [114, 136, 158]])

In [67]:
threeD

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[100, 200, 300],
        [400, 500, 600]]])

In [68]:
twoD

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
twoD[1,1]

4

In [71]:
twoD[1][1]

4

In [73]:
big = np.arange(25).reshape(5,5)
big

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [76]:
big[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])