working wuth 3d arrays


In [2]:
import numpy as np

In [4]:
three = np.arange(50).reshape(5,2,5)
three


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [5]:
three[2,0,2]

22

In [6]:
three[3,0:2,1:4]

array([[31, 32, 33],
       [36, 37, 38]])

In [9]:
three[:, :, -1]

array([[ 4,  9],
       [14, 19],
       [24, 29],
       [34, 39],
       [44, 49]])

broadcasting

In [24]:
a = np.array([[1],[2],[3]]) #(3,1)
print(a.shape)
a


(3, 1)


array([[1],
       [2],
       [3]])

In [29]:
b = np.array([[4,4,4]])
print(b.shape)
b

(1, 3)


array([[4, 4, 4]])

In [30]:
a,b = np.broadcast_arrays(a,b)

In [31]:
a

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [32]:
b

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

fancy indexing

In [9]:
f = np.empty((8,4))
f

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
for i in range(8):
    f[i]=i
f

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [11]:
f[[4,1,6]]

array([[4., 4., 4., 4.],
       [1., 1., 1., 1.],
       [6., 6., 6., 6.]])

In [12]:
g = np.arange(50).reshape(10,5)
g

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [13]:
g[[3,7,9]]

array([[15, 16, 17, 18, 19],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49]])

Transpose of an array

In [21]:
s = np.random.rand(20).reshape(4,5)
s

array([[0.82845207, 0.72319966, 0.66617536, 0.84116305, 0.56323353],
       [0.27231709, 0.59581921, 0.72250871, 0.23659482, 0.93419556],
       [0.51716316, 0.28534611, 0.74458453, 0.9253766 , 0.59011586],
       [0.37659321, 0.9718968 , 0.27582812, 0.88946428, 0.81684647]])

In [22]:
s.T

array([[0.82845207, 0.27231709, 0.51716316, 0.37659321],
       [0.72319966, 0.59581921, 0.28534611, 0.9718968 ],
       [0.66617536, 0.72250871, 0.74458453, 0.27582812],
       [0.84116305, 0.23659482, 0.9253766 , 0.88946428],
       [0.56323353, 0.93419556, 0.59011586, 0.81684647]])

In [25]:
%time
np.dot(s.T,s)

Wall time: 0 ns


array([[1.16976962, 1.27496825, 1.23759252, 1.57482898, 1.33381442],
       [1.27496825, 1.90402407, 1.39280313, 1.87781667, 1.92621968],
       [1.23759252, 1.39280313, 1.59629572, 1.66566427, 1.71487709],
       [1.57482898, 1.87781667, 1.66566427, 2.41100093, 1.96743222],
       [1.33381442, 1.92621968, 1.71487709, 1.96743222, 2.20542822]])

Universal functions

In [3]:
arrr = np.array([4,9,16,64])
np.sqrt(arrr)

array([2., 3., 4., 8.])

In [4]:
np.exp(arrr)

array([5.45981500e+01, 8.10308393e+03, 8.88611052e+06, 6.23514908e+27])

In [3]:
print("pagal")

pagal
